{{ if .Values.db_job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-db-job
  labels:
    app: {{ .Values.appName }}
  annotations:
    "helm.sh/hook": pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-failed
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [ 4000 ]
  template:
    spec:
      initContainers:
      {{- range .Values.db_job.initjobs }}
      - name: {{ . }}
        image: nareshgdevops.azurecr.io/roboshop-{{ $.Values.appName }}-db-job:latest
        env:
          - name: SCHEMA_FILE
            value: db/{{ . }}.{{ $.Values.db_job.ext }}
        envFrom:
          - secretRef:
              name: {{ $.Values.appName }}
      {{- end }}
      containers:
      {{- range .Values.db_job.jobs }}
      - name: {{ . }}
        image: nareshgdevops.azurecr.io/roboshop-{{ $.Values.appName }}-db-job:latest
        env:
          - name: SCHEMA_FILE
            value: db/{{ . }}.{{ $.Values.db_job.ext }}
        envFrom:
          - secretRef:
              name: {{ $.Values.appName }}
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: true
      {{- end }}
      restartPolicy: Never
  backoffLimit: 0
{{ end }}